In [10]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
df = pd.read_csv('onehot.csv')
orig_df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-26/boston_cocktails.csv")
df

,name,100-proof Vodka,151-Proof Rum,17-year-old J. Wray and Nephew Ltd. Rum,7-Up,Absinthe,Absinthe Substitute,Absinthe or pastis,Acai berry flavored vodka,African rum,...,orgeat or almond syrup,pineapple,pomegranate molasses (available at Middle Eastern grocers),port,powdered sugar,red wine,springs mint,sweet vermouth,thin Peeled fresh ginger,"tiki bitters, such as Bittermen's Elemakule"
0,1626,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,19th Century,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,A. J.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Absinthe Cocktail,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Absinthe Drip Cocktail,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,Yokahama Romance,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
985,Yolanda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
986,Zaza Cocktail,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
987,Zero Mint,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
988,Zombie,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df.reset_index(inplace=True)
df.set_index('name', inplace=True)
df.index

Index(['1626', '19th Century', 'A. J.', 'Absinthe Cocktail',
       'Absinthe Drip Cocktail', 'Absinthe Special Cocktail',
       'Academic Review', 'Acapulco', 'Adam and Eve', 'Adderly Cocktail',
       ...
       'Xanthia Cocktail', 'Yale Cocktail', 'Yellow Rattler',
       'Yellow Rose Of Texas', 'Yellowjacket', 'Yokahama Romance', 'Yolanda',
       'Zaza Cocktail', 'Zero Mint', 'Zombie'],
      dtype='object', name='name', length=989)

In [13]:
similarity_matrix = cosine_similarity(df)
similarity_matrix

array([[1.        , 0.2       , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.2       , 1.        , 0.36514837, ..., 0.44721314, 0.44721337,
        0.44721222],
       [0.        , 0.36514837, 1.        , ..., 0.81649574, 0.81649616,
        0.81649407],
       ...,
       [0.        , 0.44721314, 0.81649574, ..., 1.        , 0.99999846,
        0.9999959 ],
       [0.        , 0.44721337, 0.81649616, ..., 0.99999846, 1.        ,
        0.99999641],
       [0.        , 0.44721222, 0.81649407, ..., 0.9999959 , 0.99999641,
        1.        ]])

In [14]:
def get_similar_drinks(drink_name, n=5):
    if drink_name not in df.index:
        return f"Drink '{drink_name}' not found in the dataset."
    
    # Get the index of the input drink
    drink_index = df.index.get_loc(drink_name)
    
    # Get the similarity scores for the input drink
    similarity_scores = similarity_matrix[drink_index]
    
    # Get the indices of the top n most similar drinks (excluding the input drink itself)
    similar_indices = similarity_scores.argsort()[-n-1:-1][::-1]
    
    # Get the names of the similar drinks
    similar_drinks = df.index[similar_indices]
    
    return similar_drinks

In [30]:
similar_drinks = get_similar_drinks('Martini')
similar_drinks

Index(['White Cargo Cocktail', 'Vodka Martini', 'Vermouth Cassis',
       'Sake Martini', 'Rum Martini'],
      dtype='object', name='name')

In [32]:
# orig_df[orig_df['ingredient'] == 'whiskey']
orig_df[orig_df['name'] == 'Martini']

,name,category,row_id,ingredient_number,ingredient,measure
626,Martini,Cocktail Classics,192,1,Mr. Boston Gin,1 1/2 oz
627,Martini,Cocktail Classics,192,2,Dry Vermouth,3/4 oz

In [31]:
similar_drinks_ingredients = orig_df[orig_df['name'].isin(similar_drinks)]
similar_drinks_ingredients

,name,category,row_id,ingredient_number,ingredient,measure
579,Sake Martini,Cocktail Classics,178,1,Sake,1 oz
580,Sake Martini,Cocktail Classics,178,2,Mr. Boston Gin,3 oz
1080,White Cargo Cocktail,Cocktail Classics,305,1,Vanilla Ice Cream,1 oz
1081,White Cargo Cocktail,Cocktail Classics,305,2,Mr. Boston Gin,1 oz
1572,Vodka Martini,Cocktail Classics,438,1,Mr. Boston Vodka,1 1/2 oz
1573,Vodka Martini,Cocktail Classics,438,2,Dry Vermouth,3/4 oz
2197,Vermouth Cassis,Cocktail Classics,602,1,Creme de Cassis,3/4 oz
2198,Vermouth Cassis,Cocktail Classics,602,2,Dry Vermouth,1 1/2 oz
2419,Rum Martini,Rum - Daiquiris,668,1,Light Rum,2 oz
2420,Rum Martini,Rum - Daiquiris,668,2,Dry Vermouth,1 oz