In [17]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [34]:
df = pd.read_csv('onehot.csv')
orig_df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-26/boston_cocktails.csv")
df

,name,100-proof Vodka,151-Proof Rum,17-year-old J. Wray and Nephew Ltd. Rum,7-Up,Absinthe,Absinthe Substitute,Absinthe or pastis,Acai berry flavored vodka,African rum,...,orgeat or almond syrup,pineapple,pomegranate molasses (available at Middle Eastern grocers),port,powdered sugar,red wine,springs mint,sweet vermouth,thin Peeled fresh ginger,"tiki bitters, such as Bittermen's Elemakule"
0,1626,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,19th Century,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,A. J.,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Absinthe Cocktail,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Absinthe Drip Cocktail,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,Yokahama Romance,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
985,Yolanda,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
986,Zaza Cocktail,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
987,Zero Mint,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
988,Zombie,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
df.reset_index(inplace=True)
df.set_index('name', inplace=True)
df.index

Index(['1626', '19th Century', 'A. J.', 'Absinthe Cocktail',
       'Absinthe Drip Cocktail', 'Absinthe Special Cocktail',
       'Academic Review', 'Acapulco', 'Adam and Eve', 'Adderly Cocktail',
       ...
       'Xanthia Cocktail', 'Yale Cocktail', 'Yellow Rattler',
       'Yellow Rose Of Texas', 'Yellowjacket', 'Yokahama Romance', 'Yolanda',
       'Zaza Cocktail', 'Zero Mint', 'Zombie'],
      dtype='object', name='name', length=989)

In [24]:
similarity_matrix = cosine_similarity(df)
similarity_matrix

array([[1.        , 0.18257419, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.18257419, 1.        , 0.51639778, ..., 0.57734997, 0.57735012,
        0.57734938],
       [0.        , 0.51639778, 1.        , ..., 0.89442673, 0.89442696,
        0.89442582],
       ...,
       [0.        , 0.57734997, 0.89442673, ..., 1.        , 0.99999923,
        0.99999795],
       [0.        , 0.57735012, 0.89442696, ..., 0.99999923, 1.        ,
        0.99999821],
       [0.        , 0.57734938, 0.89442582, ..., 0.99999795, 0.99999821,
        1.        ]])

In [28]:
def get_similar_drinks(drink_name, n=5):
    if drink_name not in df.index:
        return f"Drink '{drink_name}' not found in the dataset."
    
    # Get the index of the input drink
    drink_index = df.index.get_loc(drink_name)
    
    # Get the similarity scores for the input drink
    similarity_scores = similarity_matrix[drink_index]
    
    # Get the indices of the top n most similar drinks (excluding the input drink itself)
    similar_indices = similarity_scores.argsort()[-n-1:-1][::-1]
    
    # Get the names of the similar drinks
    similar_drinks = df.index[similar_indices]
    
    return similar_drinks

In [32]:
similar_drinks = get_similar_drinks('Margarita')
similar_drinks

Index(['Mexicola', 'Tequila Matador', 'South Of The Border', 'Sloe Tequila',
       'Margarita Tequila'],
      dtype='object', name='name')

In [35]:
similar_drinks_ingredients = orig_df[orig_df['name'].isin(similar_drinks)]
similar_drinks_ingredients

,name,category,row_id,ingredient_number,ingredient,measure
2829,Tequila Matador,Tequila,782,1,Blanco tequila,1 1/2 oz
2830,Tequila Matador,Tequila,782,2,Pineapple Juice,2 oz
2831,Tequila Matador,Tequila,782,3,Fresh Lime Juice,1/2 oz
2888,South Of The Border,Tequila,798,1,Blanco tequila,1 oz
2889,South Of The Border,Tequila,798,2,Coffee-flavored brandy,3/4 oz
2890,South Of The Border,Tequila,798,3,Fresh Lime Juice,1/2 oz
2903,Sloe Tequila,Shooters,802,1,Blanco tequila,1 oz
2904,Sloe Tequila,Shooters,802,2,Sloe gin,1/2 oz
2905,Sloe Tequila,Shooters,802,3,Fresh Lime Juice,1/2 oz
3304,Mexicola,Tequila,905,1,Blanco tequila,2 oz
3305,Mexicola,Tequila,905,2,Fresh Lime Juice,1/2 oz
3362,Margarita Tequila,Shooters,920,2,Blanco tequila,1 1/2 oz
3363,Margarita Tequila,Shooters,920,3,Cointreau triple sec,3/4 oz
3364,Margarita Tequila,Shooters,920,4,Fresh Lime Juice,3/4 oz